AT_bufferProtection = 0.04
AT_minimumChangeForMove = 0.04
AT_changeThreshold = 0.1
AT_stableFramesForMove = 3
AT_calibrationFrames = 10
AT_scaling = 0.5
# AT_colorCurve = lambda pixel: pixel[:2]
AT_startTime = 5  # minutes
AT_incrementTime = 5  # seconds
AT_showAnything = True
AT_showEverything = True
AT_changeForQuit = 0.65
