from BoardLiveViewer import *

# TODO: ADD MORE OPTIONS AND STUFF HERE
# TODO: PLAN GUI, STAGES AND ACTIONS
# TODO: INTERACTING WITH PROGRAM
# TODO: RECORD SAMPLE VIDEOS FOR TESTING
# TODO: PGN WITH HUMAN MOVE NOTATION
# TODO: BOARD ROTATE, AUTO DETECT WHITE/BLACK SIDE
# TODO: Kivy

return_value = play("http://mizdar:alanTuning@10.249.174.222:8080/video")

print(return_value)
