[tool.briefcase]
project_name = "Notai Chess"
bundle = "uk.ac.cam"
version = "0.0.1"
url = "http://dummy.url"
license = "Proprietary"
author = 'twentyseventyone'
author_email = "rs7@op.pl"

[tool.briefcase.app.notaichess]
formal_name = "Notai Chess"
description = "Chess Game Recognition"
icon = "src/notaichess/resources/notaichess"
sources = ['src/notaichess']
requires = []


[tool.briefcase.app.notaichess.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.notaichess.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.notaichess.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.notaichess.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.notaichess.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
